# Generated by Django 3.2.5 on 2021-07-11 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercitario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='curso',
        ),
        migrations.CreateModel(
            name='ItemQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('puntuacion', models.FloatField(max_length=5)),
                ('id_ejercitario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discaltest_api.ejercitario')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discaltest_api.question')),
            ],
        ),
    ]
