# Generated by Django 3.2.5 on 2021-07-12 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0002_auto_20210711_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluprofe',
            old_name='id_profedor',
            new_name='id_profesor',
        ),
        migrations.RenameField(
            model_name='entidad',
            old_name='tip_entidad',
            new_name='tipo_entidad',
        ),
    ]
