# Generated by Django 3.2.5 on 2021-07-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0003_auto_20210711_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercitario',
            name='area',
            field=models.CharField(max_length=50),
        ),
    ]
