# Generated by Django 3.2.5 on 2021-07-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0004_alter_ejercitario_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='entidad',
            name='nro_documento',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='loggin',
            field=models.CharField(max_length=255),
        ),
    ]
