# Generated by Django 3.2.5 on 2021-07-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0005_auto_20210712_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.IntegerField(default=3),
        ),
    ]
