# Generated by Django 3.2.5 on 2021-07-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0006_profesor_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercitario',
            name='descripcion',
        ),
    ]
