# Generated by Django 3.2.7 on 2021-09-14 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0007_remove_ejercitario_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('pEsperado', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pContar', models.IntegerField(default=3)),
                ('pNumerar', models.IntegerField(default=3)),
                ('pSisNumerico', models.IntegerField(default=3)),
                ('pLogica', models.IntegerField(default=3)),
                ('pOperaciones', models.IntegerField(default=3)),
                ('pEstimTamanho', models.IntegerField(default=3)),
                ('diagnostico', models.CharField(max_length=250)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemquestion',
            name='id_ejercitario',
        ),
        migrations.RemoveField(
            model_name='itemquestion',
            name='id_question',
        ),
        migrations.RemoveField(
            model_name='profesorquestion',
            name='id_profesor',
        ),
        migrations.RemoveField(
            model_name='profesorquestion',
            name='id_question',
        ),
        migrations.DeleteModel(
            name='AluQuestion',
        ),
        migrations.DeleteModel(
            name='Ejercitario',
        ),
        migrations.DeleteModel(
            name='ItemQuestion',
        ),
        migrations.DeleteModel(
            name='ProfesorQuestion',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
