# Generated by Django 3.2.7 on 2021-09-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0008_auto_20210913_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadotest',
            name='diagnostico',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
