# Generated by Django 3.2.7 on 2021-09-14 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0009_alter_resultadotest_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='nro_documento',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
