# Generated by Django 3.2.7 on 2021-09-17 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0010_alter_entidad_nro_documento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultadoTest',
        ),
    ]
