# Generated by Django 3.2.7 on 2021-09-20 02:53

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0017_resultado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultado',
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='id_area',
            field=models.IntegerField(choices=[(1, 'Contar'), (2, 'Numerar'), (3, 'Compresion de Sistema Numérico'), (4, 'Operaciones Lógicas'), (5, 'Operaciones'), (6, 'Estimacion del Tamaño')]),
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='indicador',
            field=models.CharField(choices=[(django.db.models.aggregates.Variance, 'Contar'), (django.db.models.aggregates.Variance, 'Numerar'), (django.db.models.aggregates.Variance, 'Compresion de Sistema Numérico'), (django.db.models.aggregates.Variance, 'Operaciones Lógicas'), (django.db.models.aggregates.Variance, 'Operaciones'), (django.db.models.aggregates.Variance, 'Estimacion del Tamaño')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='observacion',
            field=models.CharField(choices=[(django.db.models.aggregates.Variance, 'Contar'), (django.db.models.aggregates.Variance, 'Numerar'), (django.db.models.aggregates.Variance, 'Compresion de Sistema Numérico'), (django.db.models.aggregates.Variance, 'Operaciones Lógicas'), (django.db.models.aggregates.Variance, 'Operaciones'), (django.db.models.aggregates.Variance, 'Estimacion del Tamaño')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resultadoitem',
            name='pObtenido',
            field=models.IntegerField(choices=[(django.db.models.aggregates.Variance, 'Contar'), (django.db.models.aggregates.Variance, 'Numerar'), (django.db.models.aggregates.Variance, 'Compresion de Sistema Numérico'), (django.db.models.aggregates.Variance, 'Operaciones Lógicas'), (django.db.models.aggregates.Variance, 'Operaciones'), (django.db.models.aggregates.Variance, 'Estimacion del Tamaño')]),
        ),
    ]
