# Generated by Django 3.2.7 on 2021-09-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0018_auto_20210919_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultadoItem',
        ),
    ]
