# Generated by Django 3.2.7 on 2021-09-20 02:58

from django.db import migrations, models
import django.db.models.aggregates
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0019_delete_resultadoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_area', models.IntegerField(choices=[(1, 'Contar'), (2, 'Numerar'), (3, 'Compresion de Sistema Numérico'), (4, 'Operaciones Lógicas'), (5, 'Operaciones'), (6, 'Estimacion del Tamaño')])),
                ('pObtenido', models.IntegerField(choices=[(django.db.models.aggregates.Variance, 'Contar'), (django.db.models.aggregates.Variance, 'Numerar'), (django.db.models.aggregates.Variance, 'Compresion de Sistema Numérico'), (django.db.models.aggregates.Variance, 'Operaciones Lógicas'), (django.db.models.aggregates.Variance, 'Operaciones'), (django.db.models.aggregates.Variance, 'Estimacion del Tamaño')])),
                ('indicador', models.CharField(choices=[(django.db.models.aggregates.Variance, 'Contar'), (django.db.models.aggregates.Variance, 'Numerar'), (django.db.models.aggregates.Variance, 'Compresion de Sistema Numérico'), (django.db.models.aggregates.Variance, 'Operaciones Lógicas'), (django.db.models.aggregates.Variance, 'Operaciones'), (django.db.models.aggregates.Variance, 'Estimacion del Tamaño')], max_length=250, null=True)),
                ('observacion', models.CharField(choices=[(django.db.models.aggregates.Variance, 'Contar'), (django.db.models.aggregates.Variance, 'Numerar'), (django.db.models.aggregates.Variance, 'Compresion de Sistema Numérico'), (django.db.models.aggregates.Variance, 'Operaciones Lógicas'), (django.db.models.aggregates.Variance, 'Operaciones'), (django.db.models.aggregates.Variance, 'Estimacion del Tamaño')], max_length=250, null=True)),
                ('id_resultadoTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discaltest_api.resultadotest')),
            ],
        ),
    ]
