# Generated by Django 3.2.7 on 2021-09-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0020_resultadoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
