# Generated by Django 3.2.7 on 2021-09-22 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0022_auto_20210919_2306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaItems',
        ),
    ]
