# Generated by Django 3.2.7 on 2021-09-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0025_alter_area_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
