# Generated by Django 3.2.7 on 2021-09-28 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0026_listaitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListaItems',
        ),
    ]
