# Generated by Django 3.2.7 on 2021-10-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0027_delete_listaitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoitem',
            name='id_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area', to='discaltest_api.area'),
        ),
    ]
