# Generated by Django 3.2.7 on 2021-10-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0029_alter_resultadoitem_id_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultadoItem',
        ),
    ]
