# Generated by Django 3.2.7 on 2021-10-02 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0031_resultadoitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadoitem',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='resultadoitem',
            table='resultadoitem',
        ),
    ]
