# Generated by Django 3.2.7 on 2021-10-03 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0033_alter_resultadoitem_id_resultadotest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoitem',
            name='id_resultadoTest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discaltest_api.resultadotest'),
        ),
    ]
