# Generated by Django 3.2.7 on 2021-10-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0034_alter_resultadoitem_id_resultadotest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultadoItem',
        ),
    ]
