# Generated by Django 3.2.7 on 2021-10-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0037_alter_entidad_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoitem',
            name='observacion',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
