# Generated by Django 3.2.7 on 2021-10-31 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0038_alter_resultadoitem_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='telefono',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='VistaResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('pObtenido', models.IntegerField()),
                ('documento', models.CharField(max_length=60, unique=True)),
                ('indicador', models.CharField(max_length=1, null=True)),
                ('observacion', models.CharField(max_length=500, null=True)),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discaltest_api.alumnos')),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discaltest_api.area')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discaltest_api.profesor')),
                ('id_resultadoTest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discaltest_api.resultadotest')),
            ],
        ),
    ]
