# Generated by Django 3.2.7 on 2021-10-31 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0039_auto_20211030_2254'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VistaResultados',
        ),
    ]
