# Generated by Django 3.2.7 on 2021-10-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0040_delete_vistaresultados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=120)),
                ('pObtenido', models.IntegerField()),
                ('nro_documento', models.CharField(max_length=60)),
                ('indicador', models.CharField(max_length=1)),
                ('observacion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'vista_resultados',
                'managed': False,
            },
        ),
    ]
