# Generated by Django 3.2.7 on 2021-10-31 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0042_auto_20211031_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VistaResultados',
        ),
    ]
