# Generated by Django 3.2.7 on 2021-10-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0045_delete_vistaresultados'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120)),
                ('pObtenido', models.IntegerField()),
                ('documento', models.IntegerField()),
                ('indicador', models.CharField(max_length=1)),
                ('observacion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'vista_resultados',
                'managed': False,
            },
        ),
    ]
