# Generated by Django 3.2.7 on 2021-10-31 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0046_vistaresultados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VistaResultados',
        ),
    ]
