# Generated by Django 3.2.7 on 2021-10-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0048_vistaresultados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=120)),
                ('nro_documento', models.CharField(max_length=20)),
                ('c_id', models.IntegerField()),
                ('c_pObtenido', models.IntegerField()),
                ('c_pesperado', models.IntegerField()),
                ('c_indicador', models.CharField(max_length=1)),
                ('c_observacion', models.CharField(max_length=500)),
                ('n_id', models.IntegerField()),
                ('n_pObtenido', models.IntegerField()),
                ('n_pesperado', models.IntegerField()),
                ('n_indicador', models.CharField(max_length=1)),
                ('n_observacion', models.CharField(max_length=500)),
                ('sn_id', models.IntegerField()),
                ('sn_pObtenido', models.IntegerField()),
                ('sn_pesperado', models.IntegerField()),
                ('sn_indicador', models.CharField(max_length=1)),
                ('sn_observacion', models.CharField(max_length=500)),
                ('opl_id', models.IntegerField()),
                ('opl_pObtenido', models.IntegerField()),
                ('opl_pesperado', models.IntegerField()),
                ('opl_indicador', models.CharField(max_length=1)),
                ('opl_observacion', models.CharField(max_length=500)),
                ('op_id', models.IntegerField()),
                ('op_pObtenido', models.IntegerField()),
                ('op_pesperado', models.IntegerField()),
                ('op_indicador', models.CharField(max_length=1)),
                ('op_observacion', models.CharField(max_length=500)),
                ('et_id', models.IntegerField()),
                ('et_pObtenido', models.IntegerField()),
                ('et_pesperado', models.IntegerField()),
                ('et_indicador', models.CharField(max_length=1)),
                ('et_observacion', models.CharField(max_length=500)),
                ('indicador', models.CharField(max_length=1)),
                ('observacion', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'v_resultados',
                'managed': False,
            },
        ),
    ]
