# Generated by Django 3.2.7 on 2021-10-31 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0051_resultados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resultados',
        ),
    ]
