# Generated by Django 3.2.7 on 2021-11-02 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0053_resultados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VistaResultados',
        ),
    ]
