# Generated by Django 3.2.7 on 2021-11-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discaltest_api', '0054_delete_vistaresultados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidad',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
